[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NPM_FLAGS = "--no-cache"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# --- [추가] 아래 헤더 블록 전체를 파일 맨 아래에 추가해주세요 ---
[[headers]]
  for = "/firebase-messaging-sw.js"
  [headers.values]
    Cache-Control = "no-cache"
    Content-Type = "application/javascript"